[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20_000
solc_version = '0.8.20'

[rpc_endpoints]
linea = "https://linea-mainnet.infura.io/v3/${INFURA_API_KEY}"
linea-testnet = "https://linea-goerli.infura.io/v3/${INFURA_API_KEY}"

[etherscan]
linea = { key = "${LINEASCAN_API_KEY}", url = "https://linea-mainnet.infura.io/v3/${INFURA_API_KEY}"}
linea-testnet = { key = "${LINEASCAN_API_KEY}", url = "https://linea-goerli.infura.io/v3/${INFURA_API_KEY}"}

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
